server:
  port: 8086
  servlet:
    path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myboot
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.leyou.pojo
