server:
  port: 8011
spring:
  application:
    name: laoban-service

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:9998/eureka
    registry-fetch-interval-seconds: 5 #5秒间隔获取服务列表
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1

